In [23]:
import pandas as pd
import time
import numpy as np

In [20]:
events = pd.read_csv('events.csv',parse_dates=True,infer_datetime_format=True)

In [21]:
    daily_events = events[events.Date != 'Daily']

In [26]:
daily_events = daily_events.replace('TBD',np.NaN)

In [33]:
daily_events['Start Time'] = daily_events['Start Time'].map(lambda x: time.strptime(x,'%H:%M %p') if not pd.isna(x) else np.NaN)

In [34]:
daily_events.sort_values('Start Time')

,Timestamp,Location,Host,Title,Date,Start Time,End Time,Description,Notes,What Is Your Contact Info? (email / phone number)
40,5/21/2019 3:38:00,Herhisensua/Red Cube,NaN,Flogger making,Friday,"(1900, 1, 1, 1, 0, 0, 0, 1, -1)",2:00 PM,Make your own flogger,NaN,vaggio@aol.com
41,5/21/2019 3:39:15,Herhisensua/Red Cube,NaN,Mummification,Saturday,"(1900, 1, 1, 1, 0, 0, 0, 1, -1)",2:00 PM,Mummification as bondage,NaN,vaggio@aol.com
71,5/21/2019 17:19:03,Martian Playground,The Hive,Nude Model Figure Class,Saturday,"(1900, 1, 1, 1, 0, 0, 0, 1, -1)",5:00 PM,The Hive will be hosting a nude model figure d...,We will provide all art supplies and materials...,melodyshah2015@gmail.com
7,5/17/2019 18:17:30,Acrodesiac Lunartics,NaN,AcroYoga Jam: Flying on the Moon,Sunday,"(1900, 1, 1, 1, 0, 0, 0, 1, -1)",NaN,Come learn to fly on the moon...literally! You...,We will provide mats and shade!,rebekah.luhrs@gmail.com
67,5/30/2019 15:44:11,In front of Spontaneous Combustion. Can't miss...,NaN,"""Space Force Space-ic Training""",Friday,"(1900, 1, 1, 2, 0, 0, 0, 1, -1)",5:00 PM,Greetings Hippies! We are Space Force: Moon Ba...,All Materials will be provided. Bring your ent...,johnjordangill@gmail.com
25,5/31/2019 0:23:37,Axis Mundi,Certified Kundalini teacher Sabrina Wells,Kundalini Yoga Meditation and Deep Relaxation ...,Friday,"(1900, 1, 1, 2, 30, 0, 0, 1, -1)",NaN,Come awaken your kundalini serpent energy with...,NaN,doinyoga@gmail.com
8,5/17/2019 18:18:30,Acrodesiac Lunartics,NaN,AcroYoga Jam: Flying on the Moon,Friday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",NaN,Come learn to fly on the moon...literally! You...,We will provide mats and shade!,rebekah.luhrs@gmail.com
9,5/17/2019 19:25:35,Acrodesiac Lunartics,NaN,AcroYoga Jam: Flying on the Moon,Saturday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",NaN,Come learn to fly on the moon...literally! You...,We will provide mats and shade!,rebekah.luhrs@gmail.com
72,5/21/2019 17:19:10,The Hive,NaN,The Pink Taco Hour!,Friday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",4:00 PM,Come visit The Hive at our camp from 3 PM to 4...,We will provide all delicious materials!,melodyshah2015@gmail.com
73,5/21/2019 17:19:14,The Hive,NaN,The Pink Taco Hour!,Saturday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",4:00 PM,Come visit The Hive at our camp from 3 PM to 4...,We will provide all delicious materials!,melodyshah2015@gmail.com
44,5/17/2019 18:38:48,Hippie Haven,NaN,Hair braiding with Hippies,Friday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",4:00 PM,We will be braiding each other’s hair! Come gi...,This will be a daily event from 3-4 and run a ...,6785366984
42,5/21/2019 3:41:36,Herhisensua/Red Cube,NaN,"Show us yours, We'll show you ours",Saturday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",4:00 PM,Show us and tell us about your favorite kinky ...,NaN,vaggio@aol.com
24,5/31/2019 0:21:51,Axis Mundi,NaN,Axis Mundi Workshop // Climbing the Cosmic Lad...,Thursday,"(1900, 1, 1, 3, 30, 0, 0, 1, -1)",4:30 PM,Axis Mundi is known as the hub or axis of the ...,3:30-4:30pm (adjustable on time – anytime from...,doinyoga@gmail.com
54,5/30/2019 1:50:56,Mermaid Oasis,NaN,Mermaid Parade,Saturday,"(1900, 1, 1, 3, 30, 0, 0, 1, -1)",NaN,All are invited to parade around the burn as M...,NaN,Picklesthemermaid@gmail.com
13,5/29/2019 11:22:00,Mermaid Oasis,Amazonite,The Many Methods to MA. ke Your Own Gem Elixir,Sunday,"(1900, 1, 1, 3, 33, 0, 0, 1, -1)",4:44 PM,Gather at the Mermaid Oasis to learn how to ut...,"Water, crystals, and vodka (to preserve your e...",Goddessajewels@gmail.com
48,5/20/2019 14:31:47,Martian Playground,NaN,Consent to get Consent: An Intoxication and Co...,Friday,"(1900, 1, 1, 4, 0, 0, 0, 1, -1)",5:00 PM,Workshop: Practical harm reduction strategies ...,NaN,ckaminski@gmail.com
46,5/19/2019 20:14:40,Martian Playground,NaN,"BDSM 101 - Negotiation, Consent, and Safety",Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",6:00 PM,A panel of experienced kinky people discuss ho...,NaN,poeticeducator@gmail.com 7704215507
27,6/5/2019 13:06:04,Zentopia,Banta,Create your prayer flag,Saturday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,"Att: sinner-saints, manual praying isn't going...",NaN,bantamax@gmail.com
26,6/5/2019 13:03:28,Zentopia,Banta,Create your prayer flag,Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,"Att: sinner-saints, manual praying isn't going...",NaN,bantamax@gmail.com
45,5/22/2019 20:24:20,Holy Catrimony,NaN,Mad Tea Party,Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",NaN,Join us at Holy Catrimony for a delightful arr...,"We're providing snacks, tea, and entertainment",alice.unrequited@gmail.com
60,6/1/2019 20:28:55,Moonspiracy,NaN,Tan n Tasty,Saturday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,Tan n Tasty: come by moonspiracy bar for tasty...,NaN,Sarahwrenea@aol.com/ 6154737025
59,6/1/2019 20:26:45,Moonspiracy,NaN,Cock-Tails,Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,cock-tails: 5:00-7:00 at moonspiracy bar\r\nwe...,NaN,Sarahwrenea@aol.com/ 6154737025
68,5/30/2019 15:44:11,In front of Spontaneous Combustion. Can't miss...,NaN,"""Space Force Space-ic Training""/Pugil Tourname...",Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,Greetings Hippies! We are Space Force: Moon Ba...,All Materials will be provided. Bring your ent...,johnjordangill@gmail.com
78,5/28/2019 15:57:30,The Tilted Hanger,NaN,Dress the LUNARTICS,Thursday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",10:00 PM,Tilted Hanger invites all (radical inclusion) ...,"All clothing provided, all you need to do is s...",kimsart788@gmail.com
49,5/30/2019 3:19:10,Miso Sexy,MerBuddah Triangle,Gerkins & Merkins,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",NaN,Join us at Miso Sexy in the MerBuddah Triangle...,"We will provide Gerkin, Merkins & pickle backs...",Callie.rickards@gmail.com 4012611679
14,5/29/2019 15:17:20,The Bermuda Pyramid,Andi Glytch,The Hoooplah!,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",8:00 PM,Hooplah skill share time!! Beginners hoop and ...,You will need to bring your own props!! I may ...,8654568978
11,5/31/2019 5:56:09,Alcoholic Alliterators,NaN,Purple Pirate Party,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",8:00 PM,Is this where I put my description? 'Cause thi...,NaN,Nina.Laverock@gmail.com
55,5/30/2019 19:10:48,Miso Sexy,NaN,Twerkshop,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",7:00 PM,Evolution of the twerk/find your rhythm and ta...,NaN,Borgmj@yahoo.com/423 631 6520
39,5/21/2019 3:42:46,Herhisensua,NaN,Kinky massage,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",10:00 PM,Kinky massage,NaN,vaggio@aol.com
56,5/29/2019 10:16:30,Miso Sexy,NaN,Be Your Burn,Saturday,"(1900, 1, 1, 7, 0, 0, 0, 1, -1)",NaN,Yoga/Meditation/Intention Setting,NaN,3375347948
...,...,...,...,...,...,...,...,...,...,...
18,5/31/2019 0:09:58,Axis Mundi,NaN,Morning Yoga with Hard Left,Friday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Axis Mundi will hold an All Levels Yoga sessio...,We will provide mats and props,doinyoga@gmail.com/6789837717
58,5/30/2019 4:40:04,Moonspiracy,NaN,Heart Chakra Kundalini,Friday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,This is short all-level kundalini practice tha...,Mats and blocks are suggested but no materials...,8652015231
22,5/31/2019 0:16:17,Axis Mundi,NaN,Multi-Sensory Meditation Experience ~ Mental I...,Saturday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Are you ready to go on a journey?\r\n Join Axi...,NaN,doinyoga@gmail.com
52,5/18/2019 2:19:50,Mermaid Oasis,NaN,Flow n Juice,Friday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Yoga practice then drink fresh pressed juice,Bring a Yoga mat,828-380-2570 or oweejay@gmail.com
35,5/31/2019 3:36:47,Headroom / Moonspiracy,NaN,Kava with 'Ohana,Thursday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Drink kava and talk story with Hawaii Lunartic...,We will provide the Kava and serving bowls!,gabi@tothemoonburn.com
53,5/18/2019 2:22:43,Mermaid Oasis,NaN,Sunbathing Yin Yoga,Sunday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Yin Yoga in the sunshine,Bring a Yoga mat,828-380-2570
10,5/19/2019 15:44:13,Acrodesiac Lunartics,NaN,Black Light Body Paint Acro,Friday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Acrodesiac Lunartics' Magical Yoga Space will ...,Black light body paint and mats provided,joepyle2@gmail.com
21,NaN,Axis Mundi,NaN,Multi-Sensory Meditation Experience ~ Mental I...,Friday,"(1900, 1, 1, 10, 30, 0, 0, 1, -1)",10:50 AM,Are you ready to go on a journey?\r\n Join Axi...,"We will provide essentials oils, digital visua...",doinyoga@gmail.com
51,5/30/2019 13:45:17,Miso Sexy,MerBuddah Triangle,Kundalini Yoga w/Siri Amrit,Friday,"(1900, 1, 1, 10, 30, 0, 0, 1, -1)",11:30 AM,Yoga & Meditation,NaN,8653520207
50,5/30/2019 17:52:40,Miso Sexy,MerBuddah Triangle,Qi Gong,Saturday,"(1900, 1, 1, 10, 30, 0, 0, 1, -1)",NaN,Qi Gong assists the free flow of energy throug...,NaN,amarnoth@gmail.com 8562286192
29,5/29/2019 3:40:04,Martian Playground,Coreythrowsthings,Freeform radicaly inclusice energetic new danc...,Saturday,"(1900, 1, 1, 10, 30, 0, 0, 1, -1)",12:00 PM,"Open skillshare to learn new flow arts, dance,...",I'll have a few extra props. But please bring ...,Foster8910@live.com/ 404 717 2344
75,NaN,(not sure yet?) still waiting on placement,NaN,The Lunar Yearbook,Friday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",2:00 PM,Making a highschool style yearbook and take pe...,NaN,NaN
76,NaN,(not sure yet?) still waiting on placement,NaN,The Lunar Yearbook,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",2:00 PM,Making a highschool style yearbook and take pe...,NaN,NaN
77,NaN,(not sure yet?) still waiting on placement,NaN,The Lunar Yearbook,Sunday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",2:00 PM,Making a highschool style yearbook and take pe...,NaN,NaN
79,5/28/2019 15:59:37,The Tilted Hanger,NaN,Tilted Hanger Dresses the Lunartics,Friday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",4:00 PM,Tilted Hanger invites all (radical inclusion) ...,"All clothing provided, all you need to do is s...",kimsart788@gmail.com
70,5/21/2019 17:18:54,Martian Playground,The Hive,Nude Model Figure Class,Friday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",1:00 PM,The Hive will be hosting a nude model figure d...,We will provide all art supplies and materials...,melodyshah2015@gmail.com
38,5/21/2019 3:36:42,Herhisensua,NaN,Sensual four hand massage,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",4:00 PM,Sensual massage,NaN,vaggio@aol.com
62,5/31/2019 3:32:21,Alcoholic Alliterators,Ocelot,Shove a tennis ball up under your butt,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",5:00 PM,Have you ever felt the endorphin rush from a t...,"Yes, I have the tennis balls",stephanie.n.dykes@gmail.com / 706-346-7641
37,5/21/2019 3:35:46,Herhisensua,NaN,Sensual four hand massage,Friday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",4:00 PM,Sensual massage,NaN,vaggio@aol.com
80,5/28/2019 16:01:07,The Tilted Hanger,NaN,Tilted Hanger Dresses the Lunartics,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",4:00 PM,Tilted Hanger invites all (radical inclusion) ...,"All clothing provided, all you need to do is s...",kimsart788@gmail.com
36,5/21/2019 3:34:54,Herhisensua,NaN,Sensual four hand massage,Thursday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",4:00 PM,Sensual massage,NaN,vaggio@aol.com
66,5/22/2019 20:25:21,"In the middle of the river, can't miss it!",NaN,BAR[ge] Open Hours,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",7:00 PM,Come get refreshed on the BAR[ge]! H-F-S 11A -...,Bring a cup.,danielgoodridge85@gmail.com
23,5/31/2019 0:17:37,Axis Mundi,NaN,Empathy vs. Sympathy avoiding karmic entanglem...,Friday,"(1900, 1, 1, 11, 30, 0, 0, 1, -1)",NaN,Learn to use your energy and powers wisely. Le...,NaN,doinyoga@gmail.com
64,6/1/2019 18:19:25,Martian Playground,Rhythm Sin Mews,Consciousness Ascension & Soul Tribes: Taking ...,Saturday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",NaN,"Greetings fellow extraterrestrials, I am Rhyth...",NaN,"briana.grace.ashbrook@gmail.com, 470-358-4312"
57,5/23/2019 0:21:36,Moonspiracy,NaN,Disco Brunch,Saturday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",NaN,A yearly tradition since Alchemy many moons ag...,Champagne and juice will be provided,Jeff Mohney jmoney386@yahoo.com
30,6/1/2019 1:39:27,Department of Synergy,NaN,A Berry Delicious Time,Thursday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",2:00 PM,Come try out miracle berries! They turn bitte...,NaN,mcoletti@gmail.com / 202 320 6321
33,6/1/2019 2:07:30,Department of Synergy,NaN,Sciencing the 💩 Out of Your 🔥,Saturday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",2:00 PM,"Come learn how the sun makes rainbows, how to ...",NaN,mcoletti@gmail.com / 202 320 6321
1,5/18/2019 4:56:38,Launchpad,2019 Greeters Team,Burner 101 ”learn to burn”,Saturday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",NaN,"An interactive, fun, classroom style burner ed...",NaN,Funsizedj@yahoo.com
0,5/18/2019 3:51:16,Launchpad,2019 Greeters Team,Burner 101 ”learn to burn”,Friday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",NaN,"An interactive, fun, classroom style burner ed...",NaN,Funsizedj@yahoo.com
47,5/17/2019 18:33:26,Lucid Lounge on plateau.,NaN,Sound Scapes & Healing,Thursday-Saturday,NaN,NaN,We host group Sound Meditation Sessions in our...,Nothing needed but an open mind and heart.,Andrea Kerns (865-851-1143)

In [35]:
days = ['Thursday','Friday','Saturday','Sunday']

In [37]:
daily_events.Date = daily_events.Date.astype('category',ordered=True,categories=days)

/Users/mcoletti/anaconda/envs/pyae/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3296: FutureWarning: specifying 'categories' or 'ordered' in .astype() is deprecated; pass a CategoricalDtype instead
  exec(code_obj, self.user_global_ns, self.user_ns)

In [39]:
daily_events.sort_values(['Date','Start Time'])

,Timestamp,Location,Host,Title,Date,Start Time,End Time,Description,Notes,What Is Your Contact Info? (email / phone number)
24,5/31/2019 0:21:51,Axis Mundi,NaN,Axis Mundi Workshop // Climbing the Cosmic Lad...,Thursday,"(1900, 1, 1, 3, 30, 0, 0, 1, -1)",4:30 PM,Axis Mundi is known as the hub or axis of the ...,3:30-4:30pm (adjustable on time – anytime from...,doinyoga@gmail.com
78,5/28/2019 15:57:30,The Tilted Hanger,NaN,Dress the LUNARTICS,Thursday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",10:00 PM,Tilted Hanger invites all (radical inclusion) ...,"All clothing provided, all you need to do is s...",kimsart788@gmail.com
28,6/4/2019 17:49:26,Camp Poor Life Choices,NaN,Topless(ish) Taco Thursday!,Thursday,"(1900, 1, 1, 7, 0, 0, 0, 1, -1)",NaN,Food in the form of black bean and ground beef...,Bring your own plate or bowl.,archimedes313@gmail.com
74,6/1/2019 2:06:24,(not sure yet?) still waiting on placement,NaN,The Lunar Yearbook,Thursday,"(1900, 1, 1, 7, 0, 0, 0, 1, -1)",9:00 PM,Making a highschool style yearbook and take pe...,NaN,6154407922
17,5/31/2019 0:04:37,Axis Mundi,NaN,Power vs Force How to move through the world l...,Thursday,"(1900, 1, 1, 7, 30, 0, 0, 1, -1)",NaN,Understanding how social and energetic situati...,NaN,doinyoga@gmail.com/6789837717
31,6/1/2019 1:52:24,Department of Synergy,NaN,Space Bar,Thursday,"(1900, 1, 1, 8, 0, 0, 0, 1, -1)",2:00 AM,From home brews with whimsical sciency names t...,NaN,mcoletti@gmail.com / 202 320 6321
6,5/17/2019 17:58:24,Acrodesiac Lunartics,NaN,Morning Yoga,Thursday,"(1900, 1, 1, 9, 0, 0, 0, 1, -1)",NaN,"Gentle yoga flow, all levels. Come stretch and...","Bring a mat if you have one, if not, we have e...",rebekah.luhrs@gmail.com
35,5/31/2019 3:36:47,Headroom / Moonspiracy,NaN,Kava with 'Ohana,Thursday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Drink kava and talk story with Hawaii Lunartic...,We will provide the Kava and serving bowls!,gabi@tothemoonburn.com
36,5/21/2019 3:34:54,Herhisensua,NaN,Sensual four hand massage,Thursday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",4:00 PM,Sensual massage,NaN,vaggio@aol.com
30,6/1/2019 1:39:27,Department of Synergy,NaN,A Berry Delicious Time,Thursday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",2:00 PM,Come try out miracle berries! They turn bitte...,NaN,mcoletti@gmail.com / 202 320 6321
40,5/21/2019 3:38:00,Herhisensua/Red Cube,NaN,Flogger making,Friday,"(1900, 1, 1, 1, 0, 0, 0, 1, -1)",2:00 PM,Make your own flogger,NaN,vaggio@aol.com
67,5/30/2019 15:44:11,In front of Spontaneous Combustion. Can't miss...,NaN,"""Space Force Space-ic Training""",Friday,"(1900, 1, 1, 2, 0, 0, 0, 1, -1)",5:00 PM,Greetings Hippies! We are Space Force: Moon Ba...,All Materials will be provided. Bring your ent...,johnjordangill@gmail.com
25,5/31/2019 0:23:37,Axis Mundi,Certified Kundalini teacher Sabrina Wells,Kundalini Yoga Meditation and Deep Relaxation ...,Friday,"(1900, 1, 1, 2, 30, 0, 0, 1, -1)",NaN,Come awaken your kundalini serpent energy with...,NaN,doinyoga@gmail.com
8,5/17/2019 18:18:30,Acrodesiac Lunartics,NaN,AcroYoga Jam: Flying on the Moon,Friday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",NaN,Come learn to fly on the moon...literally! You...,We will provide mats and shade!,rebekah.luhrs@gmail.com
44,5/17/2019 18:38:48,Hippie Haven,NaN,Hair braiding with Hippies,Friday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",4:00 PM,We will be braiding each other’s hair! Come gi...,This will be a daily event from 3-4 and run a ...,6785366984
72,5/21/2019 17:19:10,The Hive,NaN,The Pink Taco Hour!,Friday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",4:00 PM,Come visit The Hive at our camp from 3 PM to 4...,We will provide all delicious materials!,melodyshah2015@gmail.com
48,5/20/2019 14:31:47,Martian Playground,NaN,Consent to get Consent: An Intoxication and Co...,Friday,"(1900, 1, 1, 4, 0, 0, 0, 1, -1)",5:00 PM,Workshop: Practical harm reduction strategies ...,NaN,ckaminski@gmail.com
26,6/5/2019 13:03:28,Zentopia,Banta,Create your prayer flag,Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,"Att: sinner-saints, manual praying isn't going...",NaN,bantamax@gmail.com
45,5/22/2019 20:24:20,Holy Catrimony,NaN,Mad Tea Party,Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",NaN,Join us at Holy Catrimony for a delightful arr...,"We're providing snacks, tea, and entertainment",alice.unrequited@gmail.com
46,5/19/2019 20:14:40,Martian Playground,NaN,"BDSM 101 - Negotiation, Consent, and Safety",Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",6:00 PM,A panel of experienced kinky people discuss ho...,NaN,poeticeducator@gmail.com 7704215507
59,6/1/2019 20:26:45,Moonspiracy,NaN,Cock-Tails,Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,cock-tails: 5:00-7:00 at moonspiracy bar\r\nwe...,NaN,Sarahwrenea@aol.com/ 6154737025
68,5/30/2019 15:44:11,In front of Spontaneous Combustion. Can't miss...,NaN,"""Space Force Space-ic Training""/Pugil Tourname...",Friday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,Greetings Hippies! We are Space Force: Moon Ba...,All Materials will be provided. Bring your ent...,johnjordangill@gmail.com
11,5/31/2019 5:56:09,Alcoholic Alliterators,NaN,Purple Pirate Party,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",8:00 PM,Is this where I put my description? 'Cause thi...,NaN,Nina.Laverock@gmail.com
14,5/29/2019 15:17:20,The Bermuda Pyramid,Andi Glytch,The Hoooplah!,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",8:00 PM,Hooplah skill share time!! Beginners hoop and ...,You will need to bring your own props!! I may ...,8654568978
39,5/21/2019 3:42:46,Herhisensua,NaN,Kinky massage,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",10:00 PM,Kinky massage,NaN,vaggio@aol.com
49,5/30/2019 3:19:10,Miso Sexy,MerBuddah Triangle,Gerkins & Merkins,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",NaN,Join us at Miso Sexy in the MerBuddah Triangle...,"We will provide Gerkin, Merkins & pickle backs...",Callie.rickards@gmail.com 4012611679
55,5/30/2019 19:10:48,Miso Sexy,NaN,Twerkshop,Friday,"(1900, 1, 1, 6, 0, 0, 0, 1, -1)",7:00 PM,Evolution of the twerk/find your rhythm and ta...,NaN,Borgmj@yahoo.com/423 631 6520
15,5/29/2019 23:11:41,Zentopia,Arelis,Cuddle Concent,Friday,"(1900, 1, 1, 7, 30, 0, 0, 1, -1)",NaN,Cuddling is a away we can deepen our connectio...,NaN,arelisphoto@gmail.com 4074354842
12,5/31/2019 4:56:13,Alcoholic Alliterators,NaN,The bourbon baked bean bash,Friday,"(1900, 1, 1, 8, 0, 0, 0, 1, -1)",9:00 PM,Fun and wacky,NaN,bensecrest@gmail.com/423-710-0822
32,6/1/2019 1:54:41,Department of Synergy,NaN,Space Bar,Friday,"(1900, 1, 1, 8, 0, 0, 0, 1, -1)",2:00 AM,From home brews with whimsical sciency names t...,NaN,mcoletti@gmail.com / 202 320 6321
...,...,...,...,...,...,...,...,...,...,...
42,5/21/2019 3:41:36,Herhisensua/Red Cube,NaN,"Show us yours, We'll show you ours",Saturday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",4:00 PM,Show us and tell us about your favorite kinky ...,NaN,vaggio@aol.com
73,5/21/2019 17:19:14,The Hive,NaN,The Pink Taco Hour!,Saturday,"(1900, 1, 1, 3, 0, 0, 0, 1, -1)",4:00 PM,Come visit The Hive at our camp from 3 PM to 4...,We will provide all delicious materials!,melodyshah2015@gmail.com
54,5/30/2019 1:50:56,Mermaid Oasis,NaN,Mermaid Parade,Saturday,"(1900, 1, 1, 3, 30, 0, 0, 1, -1)",NaN,All are invited to parade around the burn as M...,NaN,Picklesthemermaid@gmail.com
27,6/5/2019 13:06:04,Zentopia,Banta,Create your prayer flag,Saturday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,"Att: sinner-saints, manual praying isn't going...",NaN,bantamax@gmail.com
60,6/1/2019 20:28:55,Moonspiracy,NaN,Tan n Tasty,Saturday,"(1900, 1, 1, 5, 0, 0, 0, 1, -1)",7:00 PM,Tan n Tasty: come by moonspiracy bar for tasty...,NaN,Sarahwrenea@aol.com/ 6154737025
56,5/29/2019 10:16:30,Miso Sexy,NaN,Be Your Burn,Saturday,"(1900, 1, 1, 7, 0, 0, 0, 1, -1)",NaN,Yoga/Meditation/Intention Setting,NaN,3375347948
63,5/20/2019 21:19:51,Part of Little Bohemia,NaN,I like,Saturday,"(1900, 1, 1, 7, 0, 0, 0, 1, -1)",open ended,tie dye,Bring your own clothes or whatever only small ...,Night TimeTie-dye Play Pretties
81,NaN,Department of Synergy,Michelle MaBelle,Michelle MaBelle's Pop Up Karaoke,Saturday,"(1900, 1, 1, 8, 0, 0, 0, 1, -1)",2:00 AM,Come sing your heart out to your favorite song...,NaN,NaN
3,5/17/2019 17:54:59,Acrodesiac Lunartics,NaN,Morning Yoga,Saturday,"(1900, 1, 1, 9, 0, 0, 0, 1, -1)",NaN,"Gentle yoga flow, all levels. Come stretch and...","Bring a mat if you have one, if not, we have e...",rebekah.luhrs@gmail.com
19,5/31/2019 0:13:17,Axis Mundi,NaN,Morning Yoga with Hard Left,Saturday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Axis Mundi will hold an All Levels Yoga sessio...,We will provide mats and props,doinyoga@gmail.com/6789837717
22,5/31/2019 0:16:17,Axis Mundi,NaN,Multi-Sensory Meditation Experience ~ Mental I...,Saturday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Are you ready to go on a journey?\r\n Join Axi...,NaN,doinyoga@gmail.com
29,5/29/2019 3:40:04,Martian Playground,Coreythrowsthings,Freeform radicaly inclusice energetic new danc...,Saturday,"(1900, 1, 1, 10, 30, 0, 0, 1, -1)",12:00 PM,"Open skillshare to learn new flow arts, dance,...",I'll have a few extra props. But please bring ...,Foster8910@live.com/ 404 717 2344
50,5/30/2019 17:52:40,Miso Sexy,MerBuddah Triangle,Qi Gong,Saturday,"(1900, 1, 1, 10, 30, 0, 0, 1, -1)",NaN,Qi Gong assists the free flow of energy throug...,NaN,amarnoth@gmail.com 8562286192
38,5/21/2019 3:36:42,Herhisensua,NaN,Sensual four hand massage,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",4:00 PM,Sensual massage,NaN,vaggio@aol.com
62,5/31/2019 3:32:21,Alcoholic Alliterators,Ocelot,Shove a tennis ball up under your butt,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",5:00 PM,Have you ever felt the endorphin rush from a t...,"Yes, I have the tennis balls",stephanie.n.dykes@gmail.com / 706-346-7641
66,5/22/2019 20:25:21,"In the middle of the river, can't miss it!",NaN,BAR[ge] Open Hours,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",7:00 PM,Come get refreshed on the BAR[ge]! H-F-S 11A -...,Bring a cup.,danielgoodridge85@gmail.com
76,NaN,(not sure yet?) still waiting on placement,NaN,The Lunar Yearbook,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",2:00 PM,Making a highschool style yearbook and take pe...,NaN,NaN
80,5/28/2019 16:01:07,The Tilted Hanger,NaN,Tilted Hanger Dresses the Lunartics,Saturday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",4:00 PM,Tilted Hanger invites all (radical inclusion) ...,"All clothing provided, all you need to do is s...",kimsart788@gmail.com
1,5/18/2019 4:56:38,Launchpad,2019 Greeters Team,Burner 101 ”learn to burn”,Saturday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",NaN,"An interactive, fun, classroom style burner ed...",NaN,Funsizedj@yahoo.com
33,6/1/2019 2:07:30,Department of Synergy,NaN,Sciencing the 💩 Out of Your 🔥,Saturday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",2:00 PM,"Come learn how the sun makes rainbows, how to ...",NaN,mcoletti@gmail.com / 202 320 6321
57,5/23/2019 0:21:36,Moonspiracy,NaN,Disco Brunch,Saturday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",NaN,A yearly tradition since Alchemy many moons ag...,Champagne and juice will be provided,Jeff Mohney jmoney386@yahoo.com
64,6/1/2019 18:19:25,Martian Playground,Rhythm Sin Mews,Consciousness Ascension & Soul Tribes: Taking ...,Saturday,"(1900, 1, 1, 12, 0, 0, 0, 1, -1)",NaN,"Greetings fellow extraterrestrials, I am Rhyth...",NaN,"briana.grace.ashbrook@gmail.com, 470-358-4312"
7,5/17/2019 18:17:30,Acrodesiac Lunartics,NaN,AcroYoga Jam: Flying on the Moon,Sunday,"(1900, 1, 1, 1, 0, 0, 0, 1, -1)",NaN,Come learn to fly on the moon...literally! You...,We will provide mats and shade!,rebekah.luhrs@gmail.com
13,5/29/2019 11:22:00,Mermaid Oasis,Amazonite,The Many Methods to MA. ke Your Own Gem Elixir,Sunday,"(1900, 1, 1, 3, 33, 0, 0, 1, -1)",4:44 PM,Gather at the Mermaid Oasis to learn how to ut...,"Water, crystals, and vodka (to preserve your e...",Goddessajewels@gmail.com
4,5/17/2019 17:55:38,Acrodesiac Lunartics,NaN,Morning Yoga,Sunday,"(1900, 1, 1, 9, 0, 0, 0, 1, -1)",NaN,"Gentle yoga flow, all levels. Come stretch and...","Bring a mat if you have one, if not, we have e...",rebekah.luhrs@gmail.com
5,5/17/2019 17:56:59,Acrodesiac Lunartics,NaN,Walking Meditation with Sam,Sunday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,"A guided walking mediation, lead by Sam. Follo...",NaN,rebekah.luhrs@gmail.com
53,5/18/2019 2:22:43,Mermaid Oasis,NaN,Sunbathing Yin Yoga,Sunday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Yin Yoga in the sunshine,Bring a Yoga mat,828-380-2570
61,5/17/2019 17:28:24,Moonspiracy/Headroom Bar,NaN,Elevated Arrogant Sunday Smoothies,Sunday,"(1900, 1, 1, 10, 0, 0, 0, 1, -1)",NaN,Headroom will be serving up Smooth Tunes and S...,NaN,gabi@tothemoonburn.com
77,NaN,(not sure yet?) still waiting on placement,NaN,The Lunar Yearbook,Sunday,"(1900, 1, 1, 11, 0, 0, 0, 1, -1)",2:00 PM,Making a highschool style yearbook and take pe...,NaN,NaN
47,5/17/2019 18:33:26,Lucid Lounge on plateau.,NaN,Sound Scapes & Healing,NaN,NaN,NaN,We host group Sound Meditation Sessions in our...,Nothing needed but an open mind and heart.,Andrea Kerns (865-851-1143)

In [43]:
daily_events.Date[0:5]

0      Friday
1    Saturday
2      Friday
3    Saturday
4      Sunday
Name: Date, dtype: category
Categories (4, object): [Thursday < Friday < Saturday < Sunday]